name = "kv-cookie-admin"
main = "worker.js"
compatibility_date = "2026-06-01"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "kv-cookie-db"
database_id = "1d6954d4-73ef-4455-99b7-e064851ff7b9"