name: X Systems Hosting Auto Watch Ads & Renew

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 */6 * * *' # 每 6 小时运行一次（看广告）
    - cron: '0 8 * * *'   # 每天早上 8 点运行一次（续期）

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  watch-ads:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        npm install
        npx playwright install-deps chromium
        npx playwright install chromium

    - name: Run XSH Ad Watcher
      env:
        # XSH_USERS_JSON = [{"Discord-token":"MTM3..."}]
        XSH_USERS_JSON: ${{ secrets.XSH_USERS_JSON }}
        KV_ADMIN_URL: ${{ secrets.KV_ADMIN_URL }}
        KV_ADMIN_PASS: ${{ secrets.KV_ADMIN_PASS }}
        HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" node xsh_login.js

  renew:
    runs-on: ubuntu-latest
    needs: watch-ads

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        npm install
        npx playwright install-deps chromium
        npx playwright install chromium

    - name: Run XSH Renew
      env:
        # XSH_USERS_JSON = [{"Discord-token":"MTM3..."}]
        XSH_USERS_JSON: ${{ secrets.XSH_USERS_JSON }}
        KV_ADMIN_URL: ${{ secrets.KV_ADMIN_URL }}
        KV_ADMIN_PASS: ${{ secrets.KV_ADMIN_PASS }}
        HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        TG_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" node xsh_renew.js